# Generated by Django 4.2.29 on 2026-03-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_url', models.URLField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
