# Generated by Django 4.2.29 on 2026-03-31 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0003_playlist_to_setlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('song_info', 'Song Info'), ('tempo_key', 'Tempo/Key Lookup'), ('track_source', 'Track Source'), ('download_upload', 'Download / Upload'), ('beat_detect', 'Beat Detection'), ('quantize', 'Quantize + Click'), ('stem_separation', 'Stem Separation'), ('lyrics', 'Lyrics'), ('band_details', 'Band Details'), ('review', 'Review'), ('complete', 'Complete'), ('failed', 'Failed')], default='song_info', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('artist', models.CharField(blank=True, default='', max_length=255)),
                ('tempo', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=20)),
                ('time_signature', models.CharField(default='4/4', max_length=10)),
                ('track_source', models.CharField(default='youtube', max_length=20)),
                ('youtube_selection', models.JSONField(blank=True, default=dict)),
                ('detected_beats', models.JSONField(blank=True, default=list)),
                ('adjusted_beats', models.JSONField(blank=True, default=list)),
                ('band_details', models.JSONField(blank=True, default=dict)),
                ('lyrics_content', models.TextField(blank=True, default='')),
                ('lyric_offset_secs', models.FloatField(default=0)),
                ('bg_task_status', models.CharField(default='idle', max_length=20)),
                ('bg_task_progress', models.IntegerField(default=0)),
                ('bg_task_message', models.TextField(blank=True, default='')),
                ('staging_dir', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_wizards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
