# Generated by Django 4.2.29 on 2026-03-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_song_wizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='spotify_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='spotify_client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
