# Generated by Django 4.2.29 on 2026-03-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_spotify_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='getsongbpm_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
