# Generated by Django 5.2.12 on 2026-04-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_getsongbpm_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='songwizard',
            name='selected_stems',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
