# Generated by Django 5.2.12 on 2026-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_add_selected_stems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='getsongkey_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
