# Generated by Django 5.2.12 on 2026-05-05 06:49

from django.db import migrations, models


def copy_existing_key(apps, schema_editor):
    """Copy existing getsongkey or getsongbpm key into the new song_api_key field."""
    SiteSettings = apps.get_model('player', 'SiteSettings')
    for site in SiteSettings.objects.all():
        if not site.song_api_key:
            site.song_api_key = site.getsongkey_api_key or site.getsongbpm_api_key
            site.save(update_fields=['song_api_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_add_getsongkey_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='song_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(copy_existing_key, migrations.RunPython.noop),
    ]
