# Generated by Django 5.2.12 on 2026-05-05 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fix_review_step(apps, schema_editor):
    SongWizard = apps.get_model('player', 'SongWizard')
    SongWizard.objects.filter(current_step='review').update(current_step='stem_separation')


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_add_song_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fix_review_step, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='songwizard',
            name='current_step',
            field=models.CharField(choices=[('song_info', 'Song Info'), ('tempo_key', 'Tempo/Key Lookup'), ('lyrics', 'Lyrics'), ('band_details', 'Band Details'), ('track_source', 'Track Source'), ('download_upload', 'Download / Upload'), ('beat_detect', 'Beat Detection'), ('quantize', 'Quantize + Click'), ('stem_separation', 'Stem Separation'), ('complete', 'Complete'), ('failed', 'Failed')], default='song_info', max_length=20),
        ),
        migrations.CreateModel(
            name='StemSeparationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('selected_stems', models.JSONField(blank=True, default=list)),
                ('staging_dir', models.CharField(max_length=500)),
                ('song_dir', models.CharField(blank=True, default='', max_length=500)),
                ('tempo', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=20)),
                ('time_signature', models.CharField(default='4/4', max_length=10)),
                ('lyrics_content', models.TextField(blank=True, default='')),
                ('lyric_offset_secs', models.FloatField(default=0)),
                ('band_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stem_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
