# Generated by Django 5.2.12 on 2026-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_reorder_steps_and_queue_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songwizard',
            name='current_step',
            field=models.CharField(choices=[('song_info', 'Song Info'), ('tempo_key', 'Metadata Lookup'), ('lyrics', 'Lyrics'), ('band_details', 'Band Details'), ('track_source', 'Track Source'), ('download_upload', 'Download / Upload'), ('beat_detect', 'Beat Detection'), ('quantize', 'Quantize + Click'), ('stem_separation', 'Stem Separation'), ('complete', 'Complete'), ('failed', 'Failed')], default='song_info', max_length=20),
        ),
    ]
